---

- yum: pkg={{ packages }} state=installed

- get_url: url=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm dest=/tmp/vagrant_1.8.1_x86_64.rpm

- yum: name=/tmp/vagrant_1.8.1_x86_64.rpm state=present
